In [83]:
#استيراد المكتبات

import numpy as np
# مكتبة للتعامل مع المصفوفات والعمليات الرياضية
# بنستخدمها في معالجة البيانات الرقمية وحسابات المصفوفات بسهولة

import pandas as pd
# مكتبة للتعامل مع البيانات على شكل جداول DataFrame
# بتساعدنا نقرأ الملفات (CSV, Excel) ونعمل تحليل وتنظيف للبيانات

import matplotlib.pyplot as plt
# مكتبة لرسم الرسوم البيانية والمخططات البيانية (2D plots)

import seaborn as sns
# مكتبة مبنية على matplotlib للرسم البياني بأسلوب أجمل وأسهل للتحليل البصري للبيانات

from sklearn.model_selection import train_test_split
# train_test_split: بتقسم البيانات لبيانات تدريب وبيانات اختبار لتقييم أداء النماذج

from sklearn.metrics import confusion_matrix , accuracy_score,classification_report,r2_score,mean_squared_error
# confusion_matrix: مصفوفة الالتباس لمعرفة عدد التوقعات الصحيحة والخاطئة
# accuracy_score: دقة النموذج (نسبة التوقعات الصحيحة)
# classification_report: تقرير عن الدقة والاستدعاء وF1-score لكل فئة
# r2_score: مقياس جودة النموذج في الانحدار (Regression)
# mean_squared_error: متوسط مربع الخطأ للانحدار

from sklearn.preprocessing import PolynomialFeatures,StandardScaler,MinMaxScaler, LabelEncoder
# PolynomialFeatures: بتستخدم لإنشاء ميزات متعددة الحدود (Polynomial Features) لتحسين النماذج الغير خطية
# StandardScaler: بتستخدم لتوحيد البيانات (Scaling) بحيث المتوسط = 0 والانحراف المعياري = 1، وده بيساعد النماذج تتعلم أفضل
# MinMaxScaler: أداة لعمل Scaling للبيانات بحيث تتحول القيم لمدى محدد (عادة بين 0 و 1)
# LabelEncoder: تستخدم لتحويل القيم الفئوية (نصية) إلى قيم رقمية

from sklearn.decomposition import PCA
# PCA: اختصار ل Principal Component Analysis
# طريقة لتقليل أبعاد البيانات (Dimensionality Reduction) مع الحفاظ على أكبر قدر من المعلومات

from sklearn.linear_model import LogisticRegression
# LogisticRegression: خوارزمية تصنيف (Classification) بتستخدم للتنبؤ بالنتائج الثنائية (0 أو 1)

from sklearn.tree import DecisionTreeClassifier,plot_tree,DecisionTreeRegressor
# .tree مكتبه التفرعات
# DecisionTreeClassifier: نموذج شجرة قرار للتصنيف (Classification)
# plot_tree: دالة لرسم شجرة القرار
# DecisionTreeRegressor: نموذج شجرة قرار للانحدار (Regression)

from sklearn.svm import SVC,SVR
# SVM: اختصار لمكتبه Support Vector Machine
# SVC: اختصار ل Support Vector Classifier، للتصنيف باستخدام خوارزمية SVM
# SVR: اختصار ل Support Vector Regressor، للانحدار باستخدام SVM

from sklearn.neighbors import KNeighborsClassifier
# KNeighborsClassifier: خوارزمية K-Nearest Neighbors للتصنيف بناءً على أقرب الجيران

from sklearn.ensemble import  RandomForestClassifier,GradientBoostingClassifier,AdaBoostClassifier,StackingClassifier,BaggingClassifier,RandomForestRegressor
# RandomForestClassifier: نموذج غابة عشوائية للتصنيف
# GradientBoostingClassifier: نموذج Boosting تدريجي للتصنيف
# AdaBoostClassifier: نموذج Boosting يعتمد على تعديل الأوزان للأخطاء
# StackingClassifier: دمج عدة نماذج تصنيف للحصول على نموذج أقوى
# BaggingClassifier: نموذج Bagging لتجميع نتائج عدة نماذج وتقليل التشتت (Variance)
# RandomForestRegressor: نموذج غابة عشوائية للانحدار

from sklearn.naive_bayes import GaussianNB,MultinomialNB,BernoulliNB
# GaussianNB: نموذج Naive Bayes للتصنيف مع بيانات مستمرة تتبع التوزيع الطبيعي
# MultinomialNB: نموذج Naive Bayes للتصنيف مع بيانات عدّدية (مثل النصوص)
# BernoulliNB: نموذج Naive Bayes للتصنيف مع بيانات ثنائية (0 أو 1)

from sklearn.linear_model import Lasso,Ridge,LinearRegression
# Lasso: نموذج انحدار خطي مع Regularization L1 لتقليل الأبعاد واختيار الميزات
# Ridge: نموذج انحدار خطي مع Regularization L2 لتقليل Overfitting
# LinearRegression: نموذج الانحدار الخطي البسيط للتنبؤ بالقيم المستمرة

from sklearn.cluster import KMeans
# KMeans: خوارزمية لتجميع البيانات (Clustering)
# بتقسم البيانات لعدد معين من المجموعات (Clusters) على حسب التشابه بين النقاط
# مثال: لو عايز تقسم العملاء لأنواع مختلفة حسب تصرفاتهم بدون ما يكون عندك Label

# **EDA**

In [84]:
# Load training and testing datasets from CSV files
df_train = pd.read_csv('/content/train.csv')
df_test = pd.read_csv('/content/test.csv')

In [85]:
# Display the first 5 rows of the test dataset
df_test.head()

,id,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome
0,750000,32,blue-collar,married,secondary,no,1397,yes,no,unknown,21,may,224,1,-1,0,unknown
1,750001,44,management,married,tertiary,no,23,yes,no,cellular,3,apr,586,2,-1,0,unknown
2,750002,36,self-employed,married,primary,no,46,yes,yes,cellular,13,may,111,2,-1,0,unknown
3,750003,58,blue-collar,married,secondary,no,-1380,yes,yes,unknown,29,may,125,1,-1,0,unknown
4,750004,28,technician,single,secondary,no,1950,yes,no,cellular,22,jul,181,1,-1,0,unknown

In [86]:
# Display the first 5 rows of the train dataset
df_train.head()

,id,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,0,42,technician,married,secondary,no,7,no,no,cellular,25,aug,117,3,-1,0,unknown,0
1,1,38,blue-collar,married,secondary,no,514,no,no,unknown,18,jun,185,1,-1,0,unknown,0
2,2,36,blue-collar,married,secondary,no,602,yes,no,unknown,14,may,111,2,-1,0,unknown,0
3,3,27,student,single,secondary,no,34,yes,no,unknown,28,may,10,2,-1,0,unknown,0
4,4,26,technician,married,secondary,no,889,yes,no,cellular,3,feb,902,1,-1,0,unknown,1

In [87]:
# Get the number of rows and columns in the training dataset
df_train.shape

(750000, 18)

In [88]:
# Get the number of rows and columns in the testing dataset
df_test.shape

(250000, 17)

In [89]:
# Display summary information about the training dataset, including column data types and non-null counts
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 750000 entries, 0 to 749999
Data columns (total 18 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   id         750000 non-null  int64
 1   age        750000 non-null  int64
 2   job        750000 non-null  object
 3   marital    750000 non-null  object
 4   education  750000 non-null  object
 5   default    750000 non-null  object
 6   balance    750000 non-null  int64
 7   housing    750000 non-null  object
 8   loan       750000 non-null  object
 9   contact    750000 non-null  object
 10  day        750000 non-null  int64
 11  month      750000 non-null  object
 12  duration   750000 non-null  int64
 13  campaign   750000 non-null  int64
 14  pdays      750000 non-null  int64
 15  previous   750000 non-null  int64
 16  poutcome   750000 non-null  object
 17  y          750000 non-null  int64
dtypes: int64(9), object(9)
memory usage: 103.0+ MB

In [90]:
# Display summary information about the testing dataset, including column data types and non-null counts
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 17 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   id         250000 non-null  int64
 1   age        250000 non-null  int64
 2   job        250000 non-null  object
 3   marital    250000 non-null  object
 4   education  250000 non-null  object
 5   default    250000 non-null  object
 6   balance    250000 non-null  int64
 7   housing    250000 non-null  object
 8   loan       250000 non-null  object
 9   contact    250000 non-null  object
 10  day        250000 non-null  int64
 11  month      250000 non-null  object
 12  duration   250000 non-null  int64
 13  campaign   250000 non-null  int64
 14  pdays      250000 non-null  int64
 15  previous   250000 non-null  int64
 16  poutcome   250000 non-null  object
dtypes: int64(8), object(9)
memory usage: 32.4+ MB

In [91]:
# Generate descriptive statistics for the test dataset (count, mean, std, min, quartiles, and max for numeric columns)
df_test.describe()

,id,age,balance,day,duration,campaign,pdays,previous
count,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000
mean,874999.500000,40.932332,1197.426352,16.116068,255.342260,2.573548,22.280028,0.303728
std,72168.927986,10.081613,2741.520699,8.258509,271.404326,2.709661,76.915879,1.384574
min,750000.000000,18.000000,-8019.000000,1.000000,3.000000,1.000000,-1.000000,0.000000
25%,812499.750000,33.000000,0.000000,9.000000,91.000000,1.000000,-1.000000,0.000000
50%,874999.500000,39.000000,631.000000,17.000000,133.000000,2.000000,-1.000000,0.000000
75%,937499.250000,48.000000,1389.000000,21.000000,353.000000,3.000000,-1.000000,0.000000
max,999999.000000,95.000000,98517.000000,31.000000,4918.000000,58.000000,871.000000,150.000000

In [92]:
# Generate descriptive statistics for the train dataset (count, mean, std, min, quartiles, and max for numeric columns)
df_train.describe()

,id,age,balance,day,duration,campaign,pdays,previous,y
count,750000.000000,750000.000000,750000.000000,750000.000000,750000.000000,750000.000000,750000.000000,750000.000000,750000.000000
mean,374999.500000,40.926395,1204.067397,16.117209,256.229144,2.577008,22.412733,0.298545,0.120651
std,216506.495284,10.098829,2836.096759,8.250832,272.555662,2.718514,77.319998,1.335926,0.325721
min,0.000000,18.000000,-8019.000000,1.000000,1.000000,1.000000,-1.000000,0.000000,0.000000
25%,187499.750000,33.000000,0.000000,9.000000,91.000000,1.000000,-1.000000,0.000000,0.000000
50%,374999.500000,39.000000,634.000000,17.000000,133.000000,2.000000,-1.000000,0.000000,0.000000
75%,562499.250000,48.000000,1390.000000,21.000000,361.000000,3.000000,-1.000000,0.000000,0.000000
max,749999.000000,95.000000,99717.000000,31.000000,4918.000000,63.000000,871.000000,200.000000,1.000000

In [93]:
# Display the number of unique values in each column of the test dataset
df_test.nunique()

id           250000
age              76
job              12
marital           3
education         4
default           2
balance        7073
housing           2
loan              2
contact           3
day              31
month            12
duration       1620
campaign         49
pdays           518
previous         47
poutcome          4
dtype: int64

In [94]:
# Display the number of unique values in each column of the train dataset
df_train.nunique()

id           750000
age              78
job              12
marital           3
education         4
default           2
balance        8217
housing           2
loan              2
contact           3
day              31
month            12
duration       1760
campaign         52
pdays           596
previous         50
poutcome          4
y                 2
dtype: int64

In [95]:
# Count the number of missing (NaN) values in each column of the training dataset
df_train.isna().sum()

id           0
age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
y            0
dtype: int64

In [96]:
# Count the number of missing (NaN) values in each column of the testiung dataset
df_test.isna().sum()

id           0
age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
dtype: int64

# **Preprossing**

In [97]:
# Fill missing values in categorical columns with the most frequent value (mode)

numerical_cols = df_train.select_dtypes(include=np.number).columns.tolist()

# Exclude 'id' and 'y' from numerical columns to fill if they are present and numerical
if 'id' in numerical_cols:
    numerical_cols.remove('id')
if 'y' in numerical_cols:
    numerical_cols.remove('y') # 'y' is the target, usually not imputed this way

for col in numerical_cols:
    if col in df_train.columns:
        # Ensure the column is actually numeric before calculating mean
        df_train[col] = pd.to_numeric(df_train[col], errors='coerce')
        df_train[col] = df_train[col].fillna(df_train[col].mean())

# Identify categorical columns after renaming
categorical_cols = df_train.select_dtypes(include='object').columns.tolist()

for col in categorical_cols:
    if col in df_train.columns:
        # Ensure the column is object/string before calculating mode
        df_train[col] = df_train[col].astype(str) # Ensure string type
        df_train[col] = df_train[col].fillna(df_train[col].mode()[0])
# Drop rows with NaN in the target variable 'y'
df_train_cleaned = df_train.dropna(subset=['y'])

In [98]:
df_train.isna().sum()

id           0
age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
y            0
dtype: int64

In [99]:
# Identify all categorical columns in the training dataset and apply Label Encoding to convert them into numerical values.
# This ensures that machine learning models can work with the data by replacing string categories with integer codes.

categorical_cols_train = df_train.select_dtypes(include='object').columns.tolist()

le = LabelEncoder()

for col in categorical_cols_train:
    if col in df_train.columns:
        try:
            # Convert the column to string type to handle potential mixed types
            df_train[col] = df_train[col].astype(str)
            # Apply LabelEncoder
            df_train[col] = le.fit_transform(df_train[col])
        except Exception as e:
            print(f"Could not encode column {col}: {e}")
            pass # Continue to the next column if encoding fails

In [100]:
df_train.head()

,id,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,0,42,9,1,1,0,7,0,0,0,25,1,117,3,-1,0,3,0
1,1,38,1,1,1,0,514,0,0,2,18,6,185,1,-1,0,3,0
2,2,36,1,1,1,0,602,1,0,2,14,8,111,2,-1,0,3,0
3,3,27,8,2,1,0,34,1,0,2,28,8,10,2,-1,0,3,0
4,4,26,9,1,1,0,889,1,0,0,3,3,902,1,-1,0,3,1

In [101]:
# Apply StandardScaler to all numerical columns except 'id' and target 'y'

scaler = StandardScaler()
# Identify numerical columns to scale (excluding 'id' and 'y')
numerical_cols_to_scale = df_train.select_dtypes(include=np.number).columns.tolist()

if 'id' in numerical_cols_to_scale:
    numerical_cols_to_scale.remove('id')
if 'y' in numerical_cols_to_scale:
    numerical_cols_to_scale.remove('y') # 'y' is the target, not scaled for classification


if numerical_cols_to_scale:
    df_train[numerical_cols_to_scale] = scaler.fit_transform(df_train[numerical_cols_to_scale])
    print("StandardScaler applied to numerical columns in df_train.")
else:
    print("Warning: No numerical columns identified for scaling after excluding 'id' and 'y'.")

StandardScaler applied to numerical columns in df_train.

In [102]:
df_train.head()

,id,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,0,0.106310,1.436586,-0.278168,-0.322363,-0.132025,-0.422083,-1.101939,-0.403422,-0.719187,1.076594,-1.463843,-0.510829,0.155597,-0.302803,-0.223475,0.318356,0
1,1,-0.289776,-1.019724,-0.278168,-0.322363,-0.132025,-0.243316,-1.101939,-0.403422,1.460290,0.228194,0.188185,-0.261338,-0.580100,-0.302803,-0.223475,0.318356,0
2,2,-0.487819,-1.019724,-0.278168,-0.322363,-0.132025,-0.212287,0.907491,-0.403422,1.460290,-0.256606,0.848996,-0.532843,-0.212251,-0.302803,-0.223475,0.318356,0
3,3,-1.379012,1.129548,1.454215,-0.322363,-0.132025,-0.412563,0.907491,-0.403422,1.460290,1.440194,0.848996,-0.903409,-0.212251,-0.302803,-0.223475,0.318356,0
4,4,-1.478033,1.436586,-0.278168,-0.322363,-0.132025,-0.111092,0.907491,-0.403422,-0.719187,-1.589805,-0.803032,2.369319,-0.580100,-0.302803,-0.223475,0.318356,1

# **Modeling**

In [103]:
# فصل البيانات إلى المدخلات (X) والمخرجات (y)

# Drop rows with NaN in the target variable 'y'
df_train_cleaned = df_train.dropna(subset=['y'])

x = df_train_cleaned.drop('y', axis=1)
y = df_train_cleaned['y']

In [104]:

#RandomForestClassifier
'''x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
RA = RandomForestClassifier(n_estimators=100)
RA.fit(x_train, y_train)
y_pred = RA.predict(x_test)
print(accuracy_score(y_test, y_pred))'''

#LogisticRegression
'''x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)
m1 = LogisticRegression()
m1.fit(x_train,y_train)
y_pred = m1.predict(x_test)
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))'''

#BaggingClassifier
'''
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)
ba = BaggingClassifier(estimator=DecisionTreeClassifier(),n_estimators=10,random_state=42)
ba.fit(x_train,y_train)
y_pred = ba.predict(x_test)
print(accuracy_score(y_test,y_pred))'''

#AdaBoostClassifier
'''x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)
ab = AdaBoostClassifier()
ab.fit(x_train,y_train)
y_pred = ab.predict(x_test)
print(accuracy_score(y_test,y_pred))'''

#GradientBoostingClassifier
'''x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)
gb = GradientBoostingClassifier(n_estimators=50,learning_rate=0.05,max_depth=1)
gb.fit(x_train,y_train)
y_pred = gb.predict(x_test)
print(accuracy_score(y_test,y_pred))'''

#DecisionTreeClassifier
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)
de = DecisionTreeClassifier()
de.fit(x_train,y_train)
y_pred = de.predict(x_test)
print(accuracy_score(y_test,y_pred))

0.90528

In [107]:
# Create the submission DataFrame
submission_df = pd.DataFrame({
    'id': df_test['id'],
    'y': de.predict(df_test).astype(bool)
})

print("Submission DataFrame Head:")
display(submission_df.head())

Submission DataFrame Head:

       id      y
0  750000  False
1  750001  False
2  750002  False
3  750003  False
4  750004  False

In [108]:
# حفظ ملف الإخراج بصيغة CSV بدون تضمين فهرس الصفوف

submission_df.to_csv('submission5.csv', index=False)

In [106]:
# Apply the same preprocessing steps to df_test as df_train

# Handle missing values in df_test
numerical_cols_test = df_test.select_dtypes(include=np.number).columns.tolist()
# Exclude 'id' from numerical columns in test set
if 'id' in numerical_cols_test:
    numerical_cols_test.remove('id')

for col in numerical_cols_test:
    if col in df_test.columns:
        # Ensure the column is actually numeric before calculating mean
        df_test[col] = pd.to_numeric(df_test[col], errors='coerce')
        df_test[col] = df_test[col].fillna(df_test[col].mean())

# Fill missing values for categorical columns with the mode
categorical_cols_test = df_test.select_dtypes(include='object').columns.tolist()

for col in categorical_cols_test:
    if col in df_test.columns:
        # Ensure the column is object/string before calculating mode
        df_test[col] = df_test[col].astype(str) # Ensure string type
        # Calculate mode, handle potential multiple modes by taking the first
        mode_val = df_test[col].mode()
        if not mode_val.empty:
            df_test[col] = df_test[col].fillna(mode_val[0])
        else:
            # Handle case where all values are NaN
            df_test[col] = df_test[col].fillna('unknown') # or another placeholder

# Apply Label Encoding to categorical columns in df_test
# It's important to use the same mapping as the training data.
# Since we used fit_transform on the training data in a loop,
# we'll refit here for simplicity, but be aware of potential unseen labels
# in a real-world scenario, a consistent mapping or OneHotEncoding would be better.
le_test = LabelEncoder()
for col in categorical_cols_test:
     if col in df_test.columns:
        try:
            # Convert the column to string type to handle potential mixed types
            df_test[col] = df_test[col].astype(str)
            # Apply LabelEncoder
            df_test[col] = le_test.fit_transform(df_test[col])
        except Exception as e:
            print(f"Could not encode column {col} in df_test: {e}")
            pass # Continue to the next column if encoding fails


# Apply StandardScaler to numerical columns in df_test
# Use the same scaler fitted on df_train
numerical_cols_to_scale_test = df_test.select_dtypes(include=np.number).columns.tolist()
if 'id' in numerical_cols_to_scale_test:
    numerical_cols_to_scale_test.remove('id')

if numerical_cols_to_scale_test:
    df_test[numerical_cols_to_scale_test] = scaler.transform(df_test[numerical_cols_to_scale_test])
    print("StandardScaler applied to numerical columns in df_test.")
else:
    print("Warning: No numerical columns identified for scaling in df_test after excluding 'id'.")

display(df_test.head())

StandardScaler applied to numerical columns in df_test.

,id,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome
0,750000,-0.883905,-1.019724,-0.278168,-0.322363,-0.132025,0.068028,0.907491,-0.403422,1.460290,0.591794,0.848996,-0.118248,-0.580100,-0.302803,-0.223475,0.318356
1,750001,0.304353,-0.098608,-0.278168,1.094858,-0.132025,-0.416441,0.907491,-0.403422,-0.719187,-1.589805,-1.794249,1.209922,-0.212251,-0.302803,-0.223475,0.318356
2,750002,-0.487819,0.515470,-0.278168,-1.739584,-0.132025,-0.408332,0.907491,2.478794,-0.719187,-0.377806,0.848996,-0.532843,-0.212251,-0.302803,-0.223475,0.318356
3,750003,1.690653,-1.019724,-0.278168,-0.322363,-0.132025,-0.911136,0.907491,2.478794,1.460290,1.561394,0.848996,-0.481477,-0.580100,-0.302803,-0.223475,0.318356
4,750004,-1.279990,1.436586,1.454215,-0.322363,-0.132025,0.263014,0.907491,-0.403422,-0.719187,0.712994,-0.142221,-0.276014,-0.580100,-0.302803,-0.223475,0.318356